export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SET_USER = "SET_USER";

export const GOOGLE_SIGN_IN_START = "GOOGLE_SIGN_IN_START";
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_FAIL = "GOOGLE_SIGN_IN_FAIL";

// users Profile information
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_fIRST_NAME = "UPDATE_fIRST_NAME";
export const UPDATE_LAST_NAME = "UPDATE_LAST_NAME";
export const UPDATE_BIRTHDAY_NAME = "UPDATE_BIRTHDAY_NAME";
export const UPDATE_NATIONALITY = "UPDATE_NATIONALITY";
export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_MOBILE = "UPDATE_MOBILE";

// users Location
export const UPDATE_LOCATION_INFO = "UPDATE_LOCATION_INFO";
export const UPDATE_USER_COUNTRY = "UPDATE_USER_COUNTRY";
export const UPDATE_USER_CITY = "UPDATE_USER_CITY";
export const UPDATE_USER_YEARS_OF_LIVING = "UPDATE_USER_YEARS_OF_LIVING";
export const UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS";

// users Languages
export const UPDATE_LAGUAGES_INFO = "UPDATE_USER_INFO";
export const UPDATE_ENGLISH_LEVEL = "UPDATE_ENGLISH_LEVEL";

// users Passions
export const UPDATE_PASSIONS_INFO = "UPDATE_USER_INFO";
export const UPDATE_FAV_CITY_FEATURES = "UPDATE_FAV_CITY_FEATURES";
export const UPDATE_SELF_DESCRIPTION = "UPDATE_SELF_DESCRIPTION";


export const UPDATE_HOSTED_ACTIVITY = "UPDATE_HOSTED_ACTIVITY";
export const UPDATE_GUIDE_TOUR = "UPDATE_GUIDE_TOUR";

export const UPDATE_ACCESS = "UPDATE_ACCESS";

export const UPDATE_CONNECTION = "UPDATE_CONNECTION";

export const UPDATE_TITLE = "UPDATE_TITLE";
export const UPDATE_DESCRIPTION = "UPDATE_DESCRIPTION";

export const SET_SELECTED_DURATION = "SET_SELECTED_DURATION";

export const UPDATE_TRANSPORT = "UPDATE_TRANSPORT";
export const UPDATE_CAR = "UPDATE_CAR";
export const UPDATE_HOST_PROVISION = "UPDATE_HOST_PROVISION";

export const UPDATE_KIDS = "UPDATE_KIDS";
export const UPDATE_ACCESSIBILITY_FEATURES = "UPDATE_ACCESSIBILITY_FEATURES";
export const UPDATE_ACTIVITY_LEVEL = "UPDATE_ACTIVITY_LEVEL";
export const UPDATE_SKILL_LEVEL = "UPDATE_SKILL_LEVEL";
export const UPDATE_SELECTED_AGE = "UPDATE_SELECTED_AGE";

export const UPDATE_COUNTRY = "UPDATE_COUNTRY";
export const UPDATE_REGION = "UPDATE_REGION";
export const UPDATE_STREET_ADDRESS = "UPDATE_STREET_ADDRESS";
export const UPDATE_CITY = "UPDATE_CITY";
export const UPDATE_ZIP_CODE = "UPDATE_ZIP_CODE";

export const UPDATE_PUBLIC_GROUP_SIZE = "UPDATE_PUBLIC_GROUP_SIZE";
export const UPDATE_PRIVATE_GROUP_SIZE = "UPDATE_PRIVATE_GROUP_SIZE";

export const UPDATE_EXPERIENCE_HOSTING_DAYS = "UPDATE_EXPERIENCE_HOSTING_DAYS";
export const UPDATE_EXPERIENCE_HOSTING_TIME = "UPDATE_EXPERIENCE_HOSTING_TIME";

export const UPDATE_CUTOFF_TIME = "UPDATE_CUTOFF_TIME";
export const UPDATE_DAYS_REQUEST = "UPDATE_DAYS_REQUEST";

export const UPDATE_GUIDE_LICENSE = "UPDATE_GUIDE_LICENSE";

// ___________________________________________________
